---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
        - name: go-app
          image: >-
            601730047828.dkr.ecr.us-east-1.amazonaws.com/hackathon22-team17:go-app-latest
          ports:
            - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: go-app-svc
spec:
  ports:
    - port: 443
      targetPort: 4000
  selector:
    app: go-app
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-app-ingress
  annotations:
    kubernetes.io/ingress.class: nginx-public
spec:
  rules:
    - host: goapp.ncsastaging.ue1.ptc.dev
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: go-app-svc
                port:
                  number: 443
            path: /
